name: Access sites
on:
  schedule:
    - cron: '0 8 * * *'
  push:	
    branches:	
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          cypress_kong_user: ${{ secrets.kong_user }}
          cypress_kong_pass: ${{ secrets.kong_pass }}
          cypress_epic_email: ${{ secrets.epic_email }}
          cypress_epic_pass: ${{ secrets.epic_pass }}
          CYPRESS_RECORD_KEY: ${{ secrets.cypress_record_key }}
          CYPRESS_PROJECT_ID: ${{ secrets.cypress_project_id }}
