name: Access sites
on:
  push:
    branches:
      - master
  schedule:
    - cron: '1 8 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        env:
          kong_user: ${{ secrets.kong_user }}
          kong_pass: ${{ secrets.kong_pass }}
          epic_email: ${{ secrets.epic_email }}
          epic_pass: ${{ secrets.epic_pass }}
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1