name: Access sites
on:
  push:
    branches:
      - master
  schedule:
    - cron: '1 8 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        env:
          kong_user: ${{ secrets.kong_user }}
          kong_pass: ${{ secrets.kong_pass }}
          epic_email: ${{ secrets.epic_email }}
          epic_pass: ${{ secrets.epic_pass }}
          test_secret: ${{ secrets.test_secret }}
        uses: cypress-io/github-action@v1
    steps:
    - name: Hello world
      run: echo Hello world $FIRST_NAME $middle_name $Last_Name! $test_secret
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat
        test_secret: ${{ secrets.test_secret }}